
const speechToEventMap = {
    "주유": "gas",
    "주류": "gas",
    "주야": "gas",
    "중요": "gas",
    "주연": "gas",
    "주여": "gas",
    "죽여": "gas",
    "기름": "gas",
    "집에": "gas",
    "지금": "gas",
    "넣어": "gas",
    "가득": "next",
    "절반": "next",
    "만땅": "next",
    "출차": "leave",
    "출처": "leave",
    "출장": "leave",
    "술차": "leave",
    "술사": "leave",
    "차 뻬": "leave",
    "빼": "leave",
    "자폐": "leave",
    "폐": "leave",
    "가고 싶어요": "leave",
    "카드": "next",
    "계좌": "next",
    "현금": "next",
    "차": "leave",
    "날씨": "weather",
    "온도": "weather",
    "행사": "special",
    "회사": "special",
    "예": "yes",
    "아니요": "no",
    "춤": "sexy",
    "춘천": "sexy",
    "네": "yes",
    "그래": "yes",
    "싫어요": "no",
    "괜찮아요": "no",
    "됐어요": "no"

} 

module.exports = speechToEventMap